spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/corona?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: pyimagesearch

  jpa:
    hibernate:
      ddl-auto: update
      #database: mysql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

